name: 'SSH Deploy By Falling42'
description: 'Deploys application using SSH'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  jump_ssh_host:
    description: 'Jump SSH Host'
    required: true
  jump_ssh_user:
    description: 'Jump SSH User'
    required: true
  ssh_host:
    description: 'SSH Host'
    required: true
  ssh_user:
    description: 'SSH User'
    required: true
  ssh_private_key:
    description: 'SSH Private Key'
    required: true
  deploy_script:
    description: 'Path to the deployment script on the remote server'
    required: true
  service_name:
    description: 'The service name to deploy'
    required: true
  service_version:
    description: 'The service version to deploy'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run SSH Deploy Script
      run: |
        bash scripts/deploy-via-ssh.sh \
          "${{ inputs.ssh_private_key }}" \
          "${{ inputs.jump_ssh_host }}" \
          "${{ inputs.jump_ssh_user }}" \
          "${{ inputs.ssh_host }}" \
          "${{ inputs.ssh_user }}" \
          "${{ inputs.deploy_script }}" \
          "${{ inputs.service_name }}" \
          "${{ inputs.service_version }}"
      shell: bash
