name: 'Deploy via SSH'
description: 'Deploys application using SSH'
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  use_screen:
    description: 'Whether to use screen to execute command (yes or no)'
    required: false
    default: 'no'
  use_jump_host:
    description: 'Whether to use a jump host (yes or no)'
    required: false
    default: 'no'
  jump_ssh_host:
    description: 'Jump SSH Host'
    required: false
  jump_ssh_user:
    description: 'Jump SSH User'
    required: false
  jump_ssh_private_key:
    description: 'Jump SSH Private Key'
    required: false
  jump_ssh_port:
    description: 'Jump SSH Port (default: 22)'
    required: false
    default: '22'
  ssh_host:
    description: 'SSH Host'
    required: true
  ssh_user:
    description: 'SSH User'
    required: true
  ssh_private_key:
    description: 'SSH Private Key'
    required: true
  ssh_port:
    description: 'SSH Port (default: 22)'
    required: false
    default: '22'  
  execute_remote_script:
    description: 'Whether to execute the remote script (yes or no)'
    required: false
    default: 'no'
  copy_script:
    description: 'Whether to copy the soucre script from your repository (yes or no)'
    required: false
    default: 'no'  
  source_script:
    description: 'Relative path to source script in your repository'
    required: false
  deploy_script:
    description: 'Full path to the deployment script on your remote server'
    required: false
  service_name:
    description: 'The service name to deploy'
    required: false
  service_version:
    description: 'The service version to deploy'
    required: false
  transfer_files:
    description: 'Whether to transfer files to your remote server (yes or no)'
    required: false
    default: 'yes'
  source_file_path:
    description: 'Relative path to the file to upload as an artifact'
    required: false
  destination_path:
    description: 'Full path on your remote server to transfer the file to'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: falling42/ssh-deploy
        path: external-repo  # 将脚本检出到一个子目录

    - name: Run SSH Deploy Script with environment variables
      env:
        USE_SCREEN: ${{ inputs.use_screen }}
        USE_JUMP_HOST: ${{ inputs.use_jump_host }}
        JUMP_SSH_HOST: ${{ inputs.jump_ssh_host }}
        JUMP_SSH_USER: ${{ inputs.jump_ssh_user }}
        JUMP_SSH_PRIVATE_KEY: ${{ inputs.jump_ssh_private_key }}
        JUMP_SSH_PORT: ${{ inputs.jump_ssh_port }}
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
        SSH_PORT: ${{ inputs.ssh_port }}
        COPY_SCRIPT: ${{ inputs.copy_script }}
        SOURCE_SCRIPT: ${{ inputs.source_script }}
        DEPLOY_SCRIPT: ${{ inputs.deploy_script }}
        SERVICE_NAME: ${{ inputs.service_name }}
        SERVICE_VERSION: ${{ inputs.service_version }}
        EXECUTE_REMOTE_SCRIPT: ${{ inputs.execute_remote_script }}
        TRANSFER_FILES: ${{ inputs.transfer_files }}
        SOURCE_FILE_PATH: ${{ inputs.source_file_path }}
        DESTINATION_PATH: ${{ inputs.destination_path }}
      run: |
        chmod +x ./external-repo/scripts/deploy-via-ssh.sh
        ./external-repo/scripts/deploy-via-ssh.sh
      shell: bash